### ISSUE TITLE
ToolbarButton incompatible for List<JComponent>

### ISSUE THREAD

**Issue by jlpoolen** [oxygenxml/sample-plugin-workspace-access#1]
Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500
with Java 1.8 identifies an mismatch at line 177 "comp.add..."

![2019-10-08_16-05-08](https://user-images.githubusercontent.com/227313/66439861-e3320700-e9e5-11e9-8134-e781a38a2328.png)

**Comment by raducoravu** [comment]
I'm on Eclipse 4.10 and I cannot reproduce the problem. What's the version of the "oxygen-sdk" artifact ID in your pom.xml?
The ToolbarButton extends two obfuscated java classes but in the end it is an extension of JComponent so somehow the compiler probably gets confused.
If you look in the project's **target\classes\com\oxygenxml\sdksamples\workspace** folder, is a compiled version of the **CustomWorkspaceAccessPluginExtension.class** avalilable? Because this might not be a Java compilation problem, just some kind of error shown in addition by the Eclipse checks.

**Comment by jlpoolen** [comment]
The version of the "oxygen-sdk" is SDK 21.1.0.2

I created an isolated project making only the references to Oxygen jar files as depicted in the screenshot below.

![eclipse_2019-10-09_09-48-47](https://user-images.githubusercontent.com/227313/66502553-52593b00-ea7a-11e9-85f6-031045104fed.png)

I'm not understanding what you are asking re: " project's target\classes\com\oxygenxml\sdksamples\workspace".  I opened the oxygen-sdk.jar and drilled down to D:\Downloads\SyncroSoft\oxygen-sdk-21.1.0.2-all\oxygen-sdk\oxygen.jar\com\oxygenxml\workspace\ to find only a directory "api", there are no classes at that level.  I'm probably looking the wrong place, so I'll need a bit more specificity on your request.  I also have staged within Eclipse a variety of projects which I'm finding overwhelming, hence my step to isolate and create a simple project.

I have downloaded the oxygen-sdk-21.1.0.2-all.zip and unzipped it.

**Comment by jlpoolen** [comment]
I should have provided more context in my initial posting.  What I did was copy completely the two classes of this project into my project; all I did was change the package name.  The WorkspaceAccessPlugin.java has no errors, the CustomWorkspaceAccessPluginExtension.java had the single error on line 177 as depicted in the screenshot.

**Comment by AlexJitianu** [comment]
Hi,

You need to add `jide-oss-3.6.12.jar` to the class path. The `ToolbarButton` class that the compiler complains about derives from a class present in this particular jar. Without it, the full hierarchy is not detected so the compiler doesn't see it as being a `JComponent`.

**Comment by jlpoolen** [comment]
Confirmed.

Thank you.
